language: python
python: 2.7
install:
  - sudo apt-get -qq install libfreetype6-dev liblcms1-dev libwebp-dev memcached
  - wget http://nodejs.org/dist/v0.10.22/node-v0.10.22-linux-x64.tar.gz
  - tar xzvf node-v0.10.22-linux-x64.tar.gz
  - sudo ./node-v0.10.22-linux-x64/bin/npm install -g bower grunt-cli
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -c travis.cfg install download install
  - bin/buildout -N -c travis.cfg
  - cd collective/rcse/resources/dev && sudo ../../../../node-v0.10.22-linux-x64/bin/npm install && ../../../../node-v0.10.22-linux-x64/bin/bower && ../../../../node-v0.10.22-linux-x64/bin/grunt
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test && bin/code-analysis
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
